version: '3'

volumes:
  bash-history:
  bundle-cache:
  pg-data:

services:
  dev: &server
    build: .
    volumes:
      - .:/home/phantom/app
      - bash-history:/home/phantom/bash-history
      - bundle-cache:/home/phantom/.bundle
    depends_on:
      - db
    environment:
      - SERVICE_NAME=rails_app.dev

  web:
    <<: *server
    ports:
      - "3000:3000"
    command: 'rails s -b 0.0.0.0'

  db:
    image: postgres:13.2
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
    volumes:
      - .:/home/phantom/app
      - pg-data:/var/lib/postgresql/data/
